baseURL = "https://parth-paradkar.me/"
languageCode = "en-us"
title = "Parth Paradkar"
theme="archie"
# Code Highlight
pygmentsstyle = "github"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page
googleAnalytics = "UA-179536383-1"

[params]
	mode="light" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Notes on programming and life"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/parth-paradkar"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/parthparadkar_"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
